### ISSUE TITLE
AssertionError https://art.wikidata.link/save/Q19906105

### ISSUE THREAD

**Issue by Pharos-zz** [EdwardBetts/depicts#2]
URL: https://art.wikidata.link/save/Q19906105

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/depicts/app.py", line 220, in save
    assert no_existing_edit(item_id, depicts_id)
AssertionError

**Comment by EdwardBetts** [comment]
I think it is failing because you're trying to add Mordecai (Q1136380) to the painting, but it already has a statement with that depicts item.

https://www.wikidata.org/w/index.php?title=Q19906105&diff=1025282956&oldid=915192517

**Comment by Pharos-zz** [comment]
Yes, that's it, someone else had already put up one of the depicts
statements.  I tried the same painting again without the conflicting
statement, and it worked fine.
