### ISSUE TITLE
Show a more friendly error message when WDQS returns a 403 error

### ISSUE THREAD

**Issue by fuzheado** [EdwardBetts/depicts#32]
URL: https://art.wikidata.link/item/Q100159372

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/depicts/app.py", line 444, in item_page
    if not wdqs.is_artificial_physical_object(qid):
  File "/srv/depicts/depicts/wdqs.py", line 207, in is_artificial_physical_object
    bindings = run_from_template_with_cache('query/item_type.sparql', qid=qid)
  File "/srv/depicts/depicts/wdqs.py", line 46, in run_from_template_with_cache
    return run_query_with_cache(query, name=cache_name, query_template=template_name)
  File "/srv/depicts/depicts/wdqs.py", line 98, in run_query_with_cache
    r, db_query = record_query(q, query_template=query_template)
  File "/srv/depicts/depicts/wdqs.py", line 80, in record_query
    raise QueryError(params, r)
depicts.wdqs.QueryError: ({'query': 'select ?item ?itemLabel {\n  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }\n  wd:Q100159372 wdt:P31/wdt:P279* ?item .\n}', 'format': 'json'}, <Response [403]>)

**Comment by EdwardBetts** [comment]
The Wikidata query service had started returning 403 forbidden errors. Maybe some kind of rate limiting.

WDQS is answering queries again, so this URL is working, but the error handling still needs to be improved.
